DROP DATABASE IF EXISTS camagru;

CREATE DATABASE camagru;

USE camagru;

CREATE TABLE USER
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    login VARCHAR(100),
    passwd VARCHAR(128),
    mail VARCHAR(255),
    verify INT
);

CREATE TABLE PHOTO
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    id_user INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES USER(id)
);

CREATE TABLE COMMENTS
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    content VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    id_user INT NOT NULL,
    id_photo INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES USER(id),
    FOREIGN KEY (id_photo) REFERENCES PHOTO(id)
);
